/*
 * Generated by erpcgen 1.12.0 on Sat Jun  8 13:47:25 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_StepProfilerInterface_client.h"
#include "StepProfilerInterface_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;



#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
StepProfiler_client *s_StepProfiler_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(StepProfiler_client, s_StepProfiler_client);
#endif
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
StylusProfiler_client *s_StylusProfiler_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(StylusProfiler_client, s_StylusProfiler_client);
#endif

void Z_Home(void)
{
    s_StepProfiler_client->Z_Home();
}

void Y_Home(void)
{
    s_StepProfiler_client->Y_Home();
}

void Z_Run(int32_t dir)
{
    s_StepProfiler_client->Z_Run(dir);
}

void Y_Run(int32_t dir)
{
    s_StepProfiler_client->Y_Run(dir);
}

void setForce(int32_t force)
{
    s_StepProfiler_client->setForce(force);
}

int32_t getLVDTStatus(void)
{
    int32_t result;
    result = s_StepProfiler_client->getLVDTStatus();

    return result;
}

void getLVDTFreq(lvdtFreqData * data, int32_t preCount, int32_t postCount)
{
    s_StepProfiler_client->getLVDTFreq(data, preCount, postCount);
}

void MotorRun(uint8_t _motorId, uint8_t _runType, uint8_t _runDir)
{
    s_StylusProfiler_client->MotorRun(_motorId, _runType, _runDir);
}

void MotorStop(uint8_t _motorId)
{
    s_StylusProfiler_client->MotorStop(_motorId);
}

uint8_t GetMotorRunSetStatus(uint8_t _motorId)
{
    uint8_t result;
    result = s_StylusProfiler_client->GetMotorRunSetStatus(_motorId);

    return result;
}

uint8_t GetMotorStopSetStatus(uint8_t _motorId)
{
    uint8_t result;
    result = s_StylusProfiler_client->GetMotorStopSetStatus(_motorId);

    return result;
}

void MotorZero(uint8_t _motorId)
{
    s_StylusProfiler_client->MotorZero(_motorId);
}

uint8_t GetMotorZeroStatus(uint8_t _motorId)
{
    uint8_t result;
    result = s_StylusProfiler_client->GetMotorZeroStatus(_motorId);

    return result;
}

void LineCtrl(uint16_t _value)
{
    s_StylusProfiler_client->LineCtrl(_value);
}

void AmplifierTypeSwitch(uint8_t _type)
{
    s_StylusProfiler_client->AmplifierTypeSwitch(_type);
}

void SingalCheckSwitch(uint8_t _ctrl)
{
    s_StylusProfiler_client->SingalCheckSwitch(_ctrl);
}

void DataTx2PcSwitch(uint8_t _ctrl)
{
    s_StylusProfiler_client->DataTx2PcSwitch(_ctrl);
}

void initStepProfiler_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_StepProfiler_client == nullptr);
    s_StepProfiler_client = new StepProfiler_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_StepProfiler_client.isUsed());
    s_StepProfiler_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitStepProfiler_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_StepProfiler_client != nullptr)
    {
        delete s_StepProfiler_client;
        s_StepProfiler_client = nullptr;
    }
#else
    s_StepProfiler_client.destroy();
#endif
}

void initStylusProfiler_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_StylusProfiler_client == nullptr);
    s_StylusProfiler_client = new StylusProfiler_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_StylusProfiler_client.isUsed());
    s_StylusProfiler_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitStylusProfiler_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_StylusProfiler_client != nullptr)
    {
        delete s_StylusProfiler_client;
        s_StylusProfiler_client = nullptr;
    }
#else
    s_StylusProfiler_client.destroy();
#endif
}
