/*
 * Generated by erpcgen 1.12.0 on Fri Aug  2 09:54:52 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_StepProfilerInterface_common_h_)
#define _StepProfilerInterface_common_h_


#if defined(__cplusplus)
extern "C"
{
#endif
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "erpc_version.h"

#if 11200 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_STEPPROFILERINTERFACE)
#define ERPC_TYPE_DEFINITIONS_STEPPROFILERINTERFACE

// Aliases data types declarations
typedef struct lvdtFreqData lvdtFreqData;
typedef struct sysStatus sysStatus;

// Structures/unions data types declarations
struct lvdtFreqData
{
    uint32_t lengthNum;
    uint32_t folat_lengthNum;
    int32_t * frequency;
    int16_t * sin;
    int16_t * dc;
    float * mag;
    float * phase;
};

struct sysStatus
{
    uint8_t pwrOn;
    uint8_t pwrOff;
    uint8_t towerDown;
    uint8_t singleAcquisition;
    uint8_t towerUp;
    uint8_t towerHome;
    uint8_t unloadSample;
    uint8_t loadSample;
    uint8_t Err;
};


#endif // ERPC_TYPE_DEFINITIONS_STEPPROFILERINTERFACE

#if defined(__cplusplus)
}
#endif

#endif // _StepProfilerInterface_common_h_
