/*
 * Generated by erpcgen 1.12.0 on Wed Sep  4 13:11:29 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "StepProfilerInterface_interface.hpp"

#if 11200 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

StepProfiler_interface::~StepProfiler_interface(void)
{
}
StylusProfiler_interface::~StylusProfiler_interface(void)
{
}
