/*
 * Generated by erpcgen 1.12.0 on Wed Sep  4 13:11:29 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_StepProfilerInterface_interface_hpp_)
#define _StepProfilerInterface_interface_hpp_

#include "StepProfilerInterface_common.hpp"

namespace erpcShim
{


// Abstract base class for StepProfiler
class StepProfiler_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_Z_HomeId = 1;
        static const uint8_t m_Y_HomeId = 2;
        static const uint8_t m_Z_RunId = 3;
        static const uint8_t m_Y_RunId = 4;
        static const uint8_t m_setForceId = 5;
        static const uint8_t m_getLVDTStatusId = 6;
        static const uint8_t m_getLVDTFreqId = 7;

        virtual ~StepProfiler_interface(void);

        virtual void Z_Home(void) = 0;

        virtual void Y_Home(void) = 0;

        virtual void Z_Run(int32_t dir) = 0;

        virtual void Y_Run(int32_t dir) = 0;

        virtual void setForce(int32_t force) = 0;

        virtual int32_t getLVDTStatus(void) = 0;

        virtual void getLVDTFreq(lvdtFreqData * data, int32_t preCount, int32_t postCount) = 0;
private:
};

// Abstract base class for StylusProfiler
class StylusProfiler_interface
{
    public:
        static const uint8_t m_serviceId = 2;
        static const uint8_t m_MotorRunId = 1;
        static const uint8_t m_MotorStopId = 2;
        static const uint8_t m_GetMotorRunSetStatusId = 3;
        static const uint8_t m_GetMotorStopSetStatusId = 4;
        static const uint8_t m_MotorZeroId = 5;
        static const uint8_t m_GetMotorZeroStatusId = 6;
        static const uint8_t m_LineCtrlId = 7;
        static const uint8_t m_AmplifierTypeSwitchId = 8;
        static const uint8_t m_SingalCheckSwitchId = 9;
        static const uint8_t m_DataTx2PcSwitchId = 10;
        static const uint8_t m_PwrOnId = 11;
        static const uint8_t m_PwrOffId = 12;
        static const uint8_t m_TowerDownId = 13;
        static const uint8_t m_TowerUpId = 14;
        static const uint8_t m_TowerHomeId = 15;
        static const uint8_t m_UnloadSampleId = 16;
        static const uint8_t m_LoadSampleId = 17;
        static const uint8_t m_GetSysStatusId = 18;
        static const uint8_t m_SAStopId = 19;
        static const uint8_t m_SingleAcquisitionId = 20;

        virtual ~StylusProfiler_interface(void);

        virtual void MotorRun(uint8_t _motorId, uint8_t _runType, uint8_t _runDir) = 0;

        virtual void MotorStop(uint8_t _motorId) = 0;

        virtual uint8_t GetMotorRunSetStatus(uint8_t _motorId) = 0;

        virtual uint8_t GetMotorStopSetStatus(uint8_t _motorId) = 0;

        virtual void MotorZero(uint8_t _motorId) = 0;

        virtual uint8_t GetMotorZeroStatus(uint8_t _motorId) = 0;

        virtual void LineCtrl(uint16_t _value) = 0;

        virtual void AmplifierTypeSwitch(uint8_t _type) = 0;

        virtual void SingalCheckSwitch(uint8_t _ctrl) = 0;

        virtual void DataTx2PcSwitch(uint8_t _ctrl) = 0;

        virtual void PwrOn(void) = 0;

        virtual void PwrOff(void) = 0;

        virtual void TowerDown(void) = 0;

        virtual void TowerUp(void) = 0;

        virtual void TowerHome(void) = 0;

        virtual void UnloadSample(void) = 0;

        virtual void LoadSample(void) = 0;

        virtual void GetSysStatus(sysStatus * data) = 0;

        virtual void SAStop(sAStopType _flag) = 0;

        virtual void SingleAcquisition(float _sample, float _speed, float _length, float _duration, float _resolution, sAStartType _flag) = 0;
private:
};
} // erpcShim


#endif // _StepProfilerInterface_interface_hpp_
